#!/bin/bash
# Claude_start updater — pulls latest changes and refreshes the global command

set -e

COMMANDS_DIR="$HOME/.claude/commands"
HOOKS_CACHE="$HOME/.claude/claude-start/hooks"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "Claude_start updater"
echo "--------------------"

# Pull latest
cd "$SCRIPT_DIR"
git pull

# Refresh global command
cp plugins/claude-start/skills/startnew/SKILL.md "$COMMANDS_DIR/startnew.md"
echo "✓ /startnew updated to latest version"

# Cache latest hook scripts so per-project updater can find them
mkdir -p "$HOOKS_CACHE"
# (hook scripts are generated by /startnew from SKILL.md templates;
#  a future /startupdate command will use this cache to refresh existing projects)
echo "✓ Hook cache refreshed at ~/.claude/claude-start/hooks"
echo ""
echo "Note: existing project hooks are NOT updated automatically."
echo "      Per-project hook updates are tracked in OPEN_ISSUES.md."
echo ""
